#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    desafio-final-drupal-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^desafio-final-drupal\.ddev\.site$`)
      
      service: "desafio-final-drupal-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "desafio-final-drupal-redirectHttps"
    desafio-final-drupal-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^desafio-final-drupal\.ddev\.site$`)
      
      service: "desafio-final-drupal-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "desafio-final-drupal-redirectHttps"
    
    
    
    desafio-final-drupal-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^desafio-final-drupal\.ddev\.site$`)
      
      service: "desafio-final-drupal-web-80"
      ruleSyntax: v3
      
      tls: true
      
    desafio-final-drupal-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^desafio-final-drupal\.ddev\.site$`)
      
      service: "desafio-final-drupal-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    desafio-final-drupal-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    desafio-final-drupal-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-desafio-final-drupal-web:80
        
    desafio-final-drupal-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-desafio-final-drupal-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/desafio-final-drupal.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/desafio-final-drupal.key