name: ddev-desafio-final-drupal
networks:
    ddev_default:
        external: true
        name: ddev_default
    default:
        labels:
            com.ddev.platform: ddev
        name: ddev-desafio-final-drupal_default
services:
    db:
        build:
            args:
                BASE_IMAGE: ddev/ddev-dbserver-mariadb-10.11:v1.23.5
                gid: "1000"
                uid: "1000"
                username: jessica
            context: /home/jessica/workspace/ambiente-drupal/desafio-final-drupal/.ddev/.dbimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_NICE
        command: []
        container_name: ddev-desafio-final-drupal-db
        environment:
            COLUMNS: "94"
            DDEV_DATABASE: mariadb:10.11
            DDEV_DATABASE_FAMILY: mysql
            DDEV_HOSTNAME: desafio-final-drupal.ddev.site
            DDEV_PHP_VERSION: "8.3"
            DDEV_PRIMARY_URL: https://desafio-final-drupal.ddev.site
            DDEV_PROJECT: desafio-final-drupal
            DDEV_PROJECT_TYPE: drupal
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: desafio-final-drupal
            DDEV_TLD: ddev.site
            DOCKER_IP: 127.0.0.1
            GOARCH: amd64
            GOOS: linux
            HOST_DOCKER_INTERNAL_IP: 172.18.224.1
            IS_DDEV_PROJECT: "true"
            LINES: "18"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/desafio-final-drupal-db/mysql_history
            MYSQL_PWD: db
            PGDATABASE: db
            PGHOST: 127.0.0.1
            PGPASSWORD: db
            PGUSER: db
            POSTGRES_DB: db
            POSTGRES_PASSWORD: db
            POSTGRES_USER: db
            TZ: America/Sao_Paulo
            USER: jessica
        healthcheck:
            interval: 1s
            retries: 70
            start_interval: 1s
            start_period: 2m0s
            timeout: 1m10s
        hostname: desafio-final-drupal-db
        image: ddev/ddev-dbserver-mariadb-10.11:v1.23.5-desafio-final-drupal-built
        labels:
            com.ddev.app-type: drupal
            com.ddev.approot: /home/jessica/workspace/ambiente-drupal/desafio-final-drupal
            com.ddev.platform: ddev
            com.ddev.site-name: desafio-final-drupal
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 3306
        restart: "no"
        stop_grace_period: 1m0s
        user: 1000:1000
        volumes:
            - source: database
              target: /var/lib/mysql
              type: volume
              volume:
                nocopy: true
            - bind:
                create_host_path: true
              source: /home/jessica/workspace/ambiente-drupal/desafio-final-drupal/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              source: /home/jessica/workspace/ambiente-drupal/desafio-final-drupal/.ddev/db_snapshots
              target: /mnt/snapshots
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
        working_dir: /home/jessica
    web:
        build:
            args:
                BASE_IMAGE: ddev/ddev-webserver:v1.23.5
                DDEV_DATABASE: mariadb:10.11
                DDEV_PHP_VERSION: "8.3"
                gid: "1000"
                uid: "1000"
                username: jessica
            context: /home/jessica/workspace/ambiente-drupal/desafio-final-drupal/.ddev/.webimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_PTRACE
        command:
            - /pre-start.sh
        container_name: ddev-desafio-final-drupal-web
        environment:
            COLUMNS: "94"
            COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
            COREPACK_HOME: /mnt/ddev-global-cache/corepack
            DDEV_COMPOSER_ROOT: /var/www/html
            DDEV_DATABASE: mariadb:10.11
            DDEV_DATABASE_FAMILY: mysql
            DDEV_DOCROOT: web
            DDEV_FILES_DIR: /var/www/html/web/sites/default/files
            DDEV_FILES_DIRS: /var/www/html/web/sites/default/files
            DDEV_HOSTNAME: desafio-final-drupal.ddev.site
            DDEV_MUTAGEN_ENABLED: "false"
            DDEV_PHP_VERSION: "8.3"
            DDEV_PRIMARY_URL: https://desafio-final-drupal.ddev.site
            DDEV_PROJECT: desafio-final-drupal
            DDEV_PROJECT_TYPE: drupal
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: desafio-final-drupal
            DDEV_TLD: ddev.site
            DDEV_VERSION: v1.23.5
            DDEV_WEB_ENTRYPOINT: /mnt/ddev_config/web-entrypoint.d
            DDEV_WEBSERVER_TYPE: nginx-fpm
            DDEV_XDEBUG_ENABLED: "false"
            DEPLOY_NAME: local
            DOCKER_IP: 127.0.0.1
            DOCROOT: web
            DRUSH_OPTIONS_URI: https://desafio-final-drupal.ddev.site
            GOARCH: amd64
            GOOS: linux
            HOST_DOCKER_INTERNAL_IP: 172.18.224.1
            HTTP_EXPOSE: 80:80,8025:8025
            HTTPS_EXPOSE: 443:80,8026:8025
            IS_DDEV_PROJECT: "true"
            LINES: "18"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/desafio-final-drupal-web/mysql_history
            MYSQL_PWD: db
            NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
            PGDATABASE: db
            PGHOST: db
            PGPASSWORD: db
            PGUSER: db
            PHP_IDE_CONFIG: serverName=desafio-final-drupal.ddev.site
            SSH_AUTH_SOCK: /home/.ssh-agent/socket
            TZ: America/Sao_Paulo
            USER: jessica
            VIRTUAL_HOST: desafio-final-drupal.ddev.site
            npm_config_cache: /mnt/ddev-global-cache/npm
        external_links:
            - ddev-router:desafio-final-drupal.ddev.site
        extra_hosts:
            - host.docker.internal=172.18.224.1
        healthcheck:
            interval: 1s
            retries: 70
            start_interval: 1s
            start_period: 2m0s
            timeout: 1m10s
        hostname: desafio-final-drupal-web
        image: ddev/ddev-webserver:v1.23.5-desafio-final-drupal-built
        labels:
            com.ddev.app-type: drupal
            com.ddev.approot: /home/jessica/workspace/ambiente-drupal/desafio-final-drupal
            com.ddev.platform: ddev
            com.ddev.site-name: desafio-final-drupal
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 80
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 443
        restart: "no"
        user: 1000:1000
        volumes:
            - consistency: cached
              source: /home/jessica/workspace/ambiente-drupal/desafio-final-drupal
              target: /var/www/html
              type: bind
            - bind:
                create_host_path: true
              read_only: true
              source: /home/jessica/workspace/ambiente-drupal/desafio-final-drupal/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              read_only: true
              source: /home/jessica/workspace/ambiente-drupal/desafio-final-drupal/.ddev/xhprof
              target: /usr/local/bin/xhprof
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
            - source: ddev-ssh-agent_socket_dir
              target: /home/.ssh-agent
              type: volume
              volume: {}
        working_dir: /var/www/html/
volumes:
    database:
        external: true
        name: desafio-final-drupal-mariadb
    ddev-global-cache:
        external: true
        name: ddev-global-cache
    ddev-ssh-agent_socket_dir:
        external: true
        name: ddev-ssh-agent_socket_dir
